os:
- linux
- osx
language: node_js
node_js: 8
sudo: required
dist: trusty
osx_image: xcode10.2
env:
- SWIFT_VERSION=4.2.3
install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
- npm install --global --no-optional dredd
script:
- swift test
- make test
